name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

          echo "First line:"
          head -1 ~/.ssh/ec2.pem

          echo "Last line:"
          tail -1 ~/.ssh/ec2.pem

          file ~/.ssh/ec2.pem

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh -v -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "echo Connected Successfully"